Fixed display text and popover for licenses and attribution
clearlydefined/website pull request #979
Opened 2022-05-05 16:34 UTC by qtomlinson

1. Fixed popover hidden
The popover is not visible because styling from bootstrap v5.1.1 conflicted with reactjs bootstrap popover (v0.32.3, Bootstrap 3) currently used.  A visible popover in clearlyDefined UI is styled with "fade in popover left" classes. The following style from bootstrap v5.1.1 hides the popover because the popover does not have "show" class:
.fade:not(.show) {
    opacity: 0;
}
Turn off animation for popover so the conflicting styling will not be effective.

2.  The tool list is displayed in its entirety in "Tools" section.  Popover contains only duplicate information and seems redundant.  Removed ListDataRenderer to avoid pop up.

3. Fixed display text.

Task: https://github.com/clearlydefined/website/issues/950

2022-05-05 16:56 UTC, qtomlinson commented
@disulliv @mpcen ready for review.

2022-05-14 00:57 UTC, disulliv requested changes
Looks good to me besides the styling, thanks!

2022-05-14 00:57 UTC, disulliv commented on src/styles/_Popover.scss
> +  cursor: pointer;
any chance you could update the styling to match the styles of the website? Font, etc.

2022-05-20 19:34 UTC, mpcen approved these changes

2022-05-20 20:06 UTC, qtomlinson commented
See https://github.com/clearlydefined/website/pull/979/commits/a15a45232443f214a8d610fc35f097edeb688278

2022-05-20 20:39 UTC, disulliv approved these changes

2022-05-24 16:53 UTC, merged